version: "3"

services:
  zookeeper:
    image: zookeeper
    restart: always
    container_name: nas-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
    networks:
      - backend
      - frontend
  kafka:
    image: wurstmeister/kafka
    container_name: nas-kafka
    ports:
      - "9092:9092"
    networks:
      - backend
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: nas-kafka-manager
    restart: always
    ports: 
      - "9000:9000"
    networks:
      - backend
      - frontend
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
networks: 
  frontend:
    name: kafka_frontend
    driver: bridge
  backend:
    name: kafka_backend
    driver: bridge